name: E2E tests
on:
    workflow_dispatch:
        inputs:
            wp_version:
                description: Specific WordPress version to use instead the latest.
                type: string
                required: false
    schedule:
        - cron: '0 0 * * 0'
jobs:
    e2e-tests:
        strategy:
            fail-fast: false
            matrix:
                wp_plugin: ['comment-saver', 'wp-guest-bar']
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4

            - name: Setup WordPress and Playwright
              run: |
                  ./bin/env setup ${{ matrix.wp_plugin }}
                  [ -n ${{ inputs.wp_version }} ] && docker compose run --rm wp-cli wp core update --version=${{ inputs.wp_version }} --force
                  [ -n ${{ inputs.wp_version }} ] && docker compose run --rm wp-cli wp core update-db

            - name: Run E2E tests
              run: ./bin/env test ${{ matrix.wp_plugin }}

            - name: Retain failed test results
              uses: actions/upload-artifact@v4
              if: failure()
              with:
                  name: test-results-${{ matrix.wp_plugin }}
                  path: artifacts/test-results/

            - name: Shutdown environments
              if: always()
              run: ./bin/env destroy
